pid = /var/run/stunnel4.pid
cert = /etc/stunnel/stunnel.pem
# 前台不运行，启用后台模式
foreground = no

[http_proxy]
accept = 0.0.0.0:443
connect = 127.0.0.1:1081

[socks5]
accept = 0.0.0.0:8443
connect = 127.0.0.1:1082