config setup
    charondebug="ike 1, knl 1, cfg 2"
    uniqueids=no

conn ikev2-vpn
    auto=add
    compress=no
    type=tunnel
    keyexchange=ikev2
    fragmentation=yes
    forceencaps=yes
    
    # 死链检测
    dpdaction=clear
    dpddelay=300s
    rekey=no

    # 服务端配置
    left=%any
    leftid=202.182.104.239         # 必须与上面证书的 CN/SAN 一致
    leftcert=serverCert.pem
    leftsendcert=always
    # 关键：这里只推送外网全流量，交给客户端做路由过滤
    leftsubnet=0.0.0.0/0

    # 客户端配置
    right=%any
    rightid=%any
    rightauth=pubkey
    rightsourceip=10.10.10.0/24 # 分配给客户端的独立内网 IP 段
    rightdns=8.8.8.8,1.1.1.1