[Interface]
PrivateKey = mBW9CP1Aa6btR0vKu8Co8kQRTuKzGgmQchQYkGeQNEE=
Address = 10.0.0.1/24
ListenPort = 5443

# 开启流量转发（当 WireGuard 启动和关闭时自动执行）
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o enp1s0 -j MASQUERADE
PostUp   = sysctl -w net.ipv4.ip_forward=1
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.0.0.0/24 -o enp1s0 -j MASQUERADE
# PostDown = iptables -F FORWARD; iptables -t nat -F POSTROUTING
PostDown = sysctl -w net.ipv4.ip_forward=0

[Peer]
# Mac 客户端
PublicKey = GEZAA4r8Fr9d8jRZJEmqmFCcv5iqW5TCDee8iT1DRks=
AllowedIPs = 10.0.0.2/32

[Peer]
# iPhone 客户端
PublicKey = EY9SbHd2QV5/OIWJ6OdGS35fWIEK8qj+VtpniELeyjI=
AllowedIPs = 10.0.0.3/32

[Peer]
# Linux 客户端
PublicKey = XTeuhsEP0DHqFI0yLoNLcMEcY8HmWQoyoxHpoQo08ho=
AllowedIPs = 10.0.0.5/32