[Interface]
PrivateKey = yPYxcuXn9MQvLiDUb8mTZkGaP4i8YzSSz4nnTdmWvEs=
Address = 10.0.0.5/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = 5YXE9a/7cs52zTgqgBC0BDo+jXUgeVrKL6TaQst2IRE=
Endpoint = 202.182.104.239:5443
PersistentKeepalive = 30

AllowedIPs = 0.0.0.0/0, ::/0